plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/codespace/.openclaw/workspace/school-race-react/build"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/codespace/.openclaw/workspace/school-race-react"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]